/*
 * Vesktop, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and Vencord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import SettingsUi from "./components/settings/Settings";
import { VelcordLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

import type SettingsPlugin from "@vencord/types/plugins/_core/settings";

VelcordLogger.log("read if cute :3");
VelcordLogger.log("Velcord v" + VesktopNative.app.getVersion());

// TODO
const customSettingsSections = (Vencord.Plugins.plugins.Settings as typeof SettingsPlugin).customSections;

customSettingsSections.push(() => ({
    section: "Velcord",
    label: "Velcord Settings",
    element: SettingsUi,
    className: "vc-velcord-settings"
}));

// TODO: remove this legacy workaround once some time has passed
if (!Vencord.Api.Styles.vencordRootNode) {
    const style = document.createElement("style");
    style.id = "velcord-css-core";

    const terminalTheme = document.createElement("style");
    terminalTheme.id = "velcord-terminal-theme";
    terminalTheme.textContent = `
        :root {
            color-scheme: dark !important;
            --background-primary: #000000 !important;
            --background-secondary: #0b0b0b !important;
            --background-tertiary: #0f0f0f !important;
            --text-normal: #ffffff !important;
            --text-muted: #bfcf9a !important;
            --text-link: #bff77a !important;
            --text-link-hover: #e6ffb3 !important;
            --interactive-normal: #ffffff !important;
            --interactive-muted: #aaaaaa !important;
            --radius: 1px !important;
        }

        html, body, #app-mount, .app, .theme-dark {
            background-color: #000000 !important;
            color: #ffffff !important;
            font-family: 'Inconsolata', "Courier New", Consolas, monospace !important;
        }

        a { color: var(--text-link) !important; }
        a:hover { color: var(--text-link-hover) !important; }

        * { box-shadow: none !important; }

        button, input, textarea, select, summary, [role="button"] {
            background: rgba(255,255,255,0.02) !important;
            border: 1px solid rgba(255,255,255,0.06) !important;
            color: var(--text-normal) !important;
            border-radius: var(--radius) !important;
            backdrop-filter: blur(6px) saturate(120%) !important;
        }

        svg, path, circle, rect, polygon, polyline, line, ellipse { fill: #ffffff !important; stroke: #ffffff !important; }

        img { filter: grayscale(100%) brightness(1.15) contrast(1.08) !important; }

        ::selection { background: #bff77a !important; color: #000000 !important; }
    `;

    VesktopNative.app.getRendererCss().then(css => (style.textContent = css));

    document.addEventListener("DOMContentLoaded", () => document.documentElement.append(style, terminalTheme), { once: true });
}
